# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy server

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Change to server directory
        run: cd server
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
          cache: "yarn"
          cache-dependency-path: "./server/yarn.lock"
      - run: yarn install
        working-directory: ./server
      - run: yarn build
        working-directory: ./server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/next-fastify-demo
            cd server
            expect << 'END'
              spawn git fetch --all
              expect "Password:"
              send "${{ secrets.PASS_GIT_TOKEN }}\r"
              expect eof
            END
            git reset --hard origin/main
            echo "${{secrets.ENV_PRODUCTION}}" > .env
            yarn install
            yarn build
            pm2 start ecosystem.config.js
